[package]
name = "export_lib"
version = "0.1.1"
edition = "2021"

[dependencies]
csv = "1.4.0"
rust_xlsxwriter = "0.93.0"
spreadsheet-ods = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"